services:

  - type: web
    name: netassist-api

    runtime: python

    buildCommand: pip install -r requirements.txt

    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT

    envVars:
      - key: OPENAI_API_KEY
        sync: false

      - key: PINECONE_API_KEY
        sync: false

      - key: PINECONE_INDEX_NAME
        value: router-manuals

      - key: LANGCHAIN_API_KEY
        sync: false

      - key: LANGCHAIN_TRACING_V2
        value: "true"

      - key: LANGCHAIN_PROJECT
        value: NetAssist
